#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
pkill -f tint2 &
pkill -f pasystray &

xrandr --output VGA1 --left-of HDMI1

bspc monitor ^1 -d I
bspc monitor ^2 -d II SCRATCH

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_modifier mod1

feh --no-fehbg --bg-fill /home/teacher/Wallpaper/BG4 /home/teacher/Wallpaper/BG1 &
picom -b
pasystray &
nm-applet &
tint2 &
