#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor DisplayPort-1 -d M1
bspc monitor DisplayPort-2 -d M2
bspc monitor HDMI-A-0 -d TV

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

picom -b
pcmanfm --desktop & disown
nm-applet &
pasystray &
tint2 &


bspc rule -a URxvt state=floating
