#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
killall -SIGUSR1 tint2

bspc monitor DisplayPort-1 -d HOME
bspc monitor DisplayPort-2 -d DOCUMENTS
bspc monitor HDMI-A-0 -d DESKTOP SCRATCH

bspc config border_width         2
bspc config window_gap          12
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_modifier mod1
bspc config focused_border_color '#004400'
bspc config click_to_focus none

picom -b
pcmanfm --desktop & disown
nm-applet &
pasystray &
tint2 -c ~/.config/tint2/main.tint2rc &

bspc rule -a Steam monitor=^3
